// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGc4SJEqQhQRBFrnJXrU7vYudBrOT6Rw',
    appId: '1:461405600632:web:5c78b5ba0471492a50668d',
    messagingSenderId: '461405600632',
    projectId: 'together-4dc98',
    authDomain: 'together-4dc98.firebaseapp.com',
    storageBucket: 'together-4dc98.appspot.com',
    measurementId: 'G-60XZTTCS2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj7Fh50rOdQCZeSlEvDulIxEBTIgyf6sk',
    appId: '1:461405600632:android:306abf00819bc44650668d',
    messagingSenderId: '461405600632',
    projectId: 'together-4dc98',
    storageBucket: 'together-4dc98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQqA6j1b196PY4uLfvLitjfgXCgmRM0I',
    appId: '1:461405600632:ios:9b27f8eadf4bbbc950668d',
    messagingSenderId: '461405600632',
    projectId: 'together-4dc98',
    storageBucket: 'together-4dc98.appspot.com',
    iosClientId:
        '461405600632-r804unek3gmat17mmr5faj77f5b3i5ea.apps.googleusercontent.com',
    iosBundleId: 'com.levi.together',
  );
}
